version: '3.2'

services:
  influxdb:
    build: docker/influxdb
    env_file: docker/grafana/configuration.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - code-network
  grafana:
    build: docker/grafana
    env_file: docker/grafana/configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - code-network
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    build: docker/php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - code-network

volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  code-network:
    driver: bridge
